In [1]:
import pandas as pd

files = [
    "charts_albums_weekly.csv",
    "albums.csv",
    "artists.csv"
]

for file in files:
    print("\n" + "="*60)
    print(file)

    df = pd.read_csv(file)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nPreview:")
    print(df.head())

============================================================
charts_albums_weekly.csv
Shape: (2989175, 17)

Columns:
['date', 'country', 'rank', 'uri', 'album_name', 'artist_names', 'label', 'peak_rank', 'previous_rank', 'weeks_on_chart', 'consecutive_weeks', 'entry_status', 'peak_date', 'entry_rank', 'entry_date', 'release_date', 'artist_uris']

Preview:
         date country  rank                                   uri  \
0  2020-11-19      ar     1  spotify:album:3fq06DDIkadDRB9RuBb22v
1  2020-11-19      ar     2  spotify:album:0p2yf6DucEgvj8Uk8KXJJv
2  2020-11-19      ar     3  spotify:album:69iuPQsXel3luOSDNF0q2Q
3  2020-11-19      ar     4  spotify:album:6xS6mQz1fQZ6eZE654J15I
4  2020-11-19      ar     5  spotify:album:5lJqux7orBlA1QzyiBGti1

        album_name    artist_names                                 label  \
0      Afrodisíaco  Rauw Alejandro  Sony Music Latin/Duars Entertainment
1     PAPI JUANCHO          Maluma                      Sony Music Latin
2             ENOC           Ozuna                      Aura Music Corp.
3  Por Primera Vez          Camilo                      Sony Music Latin
4         YHLQMDLG       Bad Bunny               Rimas Entertainment LLC

   peak_rank  previous_rank  weeks_on_chart  consecutive_weeks entry_status  \
0          1             -1               1                  1    NEW_ENTRY
1          2             -1               1                  1    NEW_ENTRY
2          3             -1               1                  1    NEW_ENTRY
3          4             -1               1                  1    NEW_ENTRY
4          5             -1               1                  1    NEW_ENTRY

    peak_date  entry_rank  entry_date release_date  \
0  2020-11-19           1  2020-11-19   2020-11-13
1  2020-11-19           2  2020-11-19   2020-08-21
2  2020-11-19           3  2020-11-19   2020-09-04
3  2020-11-19           4  2020-11-19   2020-04-17
4  2020-11-19           5  2020-11-19   2020-02-29

                             artist_uris
0  spotify:artist:1mcTU81TzQhprhouKaTkpq
1  spotify:artist:1r4hJ1h58CWwUQe3MxPuau
2  spotify:artist:1i8SpTcr7yvPOmcqrbnVXY
3  spotify:artist:28gNT5KBp7IjEOQoevXf9N
4  spotify:artist:4q3ewBCX7sLwd24euuV69X

============================================================
albums.csv
Shape: (26190, 6)

Columns:
['album_uri', 'album_name', 'artist_names', 'artist_uris', 'label', 'release_date']

Preview:
                              album_uri       album_name    artist_names  \
0  spotify:album:3fq06DDIkadDRB9RuBb22v      Afrodisíaco  Rauw Alejandro
1  spotify:album:0p2yf6DucEgvj8Uk8KXJJv     PAPI JUANCHO          Maluma
2  spotify:album:69iuPQsXel3luOSDNF0q2Q             ENOC           Ozuna
3  spotify:album:6xS6mQz1fQZ6eZE654J15I  Por Primera Vez          Camilo
4  spotify:album:5lJqux7orBlA1QzyiBGti1         YHLQMDLG       Bad Bunny

                             artist_uris  \
0  spotify:artist:1mcTU81TzQhprhouKaTkpq
1  spotify:artist:1r4hJ1h58CWwUQe3MxPuau
2  spotify:artist:1i8SpTcr7yvPOmcqrbnVXY
3  spotify:artist:28gNT5KBp7IjEOQoevXf9N
4  spotify:artist:4q3ewBCX7sLwd24euuV69X

                                  label release_date
0  Sony Music Latin/Duars Entertainment   2020-11-13
1                      Sony Music Latin   2020-08-21
2                      Aura Music Corp.   2020-09-04
3                      Sony Music Latin   2020-04-17
4              Rimas Entertainment LLC.   2020-02-29

============================================================
artists.csv
Shape: (73955, 6)

Columns:
['artist_uri', 'artist_name', 'monthly_listeners', 'monthly_listeners_rank', 'monthly_listeners_peak_rank', 'monthly_listeners_peak_listeners']

Preview:
                              artist_uri     artist_name  monthly_listeners  \
0  spotify:artist:5csAaiFcC1qKkVPgUJfXID     Zulu Queens                NaN
1  spotify:artist:2h9NlcdGxIEnnh5aQuSeZ1  Lwah Ndlunkulu          1193598.0
2  spotify:artist:5kwZB1xNLgB3lln1JGS2B9          MaWhoo          2847892.0
3  spotify:artist:1UwTwoC4T1i6vzwsQgIWB0            Feza          1838394.0
4  spotify:artist:6Wqpl1YTjgy5TiTluzFzjx     Tman Xpress          1753888.0

   monthly_listeners_rank  monthly_listeners_peak_rank  \
0                     NaN                          NaN
1                 12583.0                          NaN
2                  5651.0                          NaN
3                  8566.0                          NaN
4                  8965.0                          NaN

   monthly_listeners_peak_listeners
0                               NaN
1                         1236495.0
2                         2868014.0
3                         1885686.0
4                         1753888.0

In [2]:
charts = pd.read_csv(
    "charts_albums_weekly.csv",
    low_memory=False
)

charts.memory_usage(deep=True).sum() / 1024**2

np.float64(2173.496180534363)

In [3]:
charts["date"] = pd.to_datetime(charts["date"])

print(charts["date"].min())
print(charts["date"].max())

2020-10-22 00:00:00
2026-10-08 00:00:00

In [4]:
charts["country"].nunique()

51

In [5]:
sorted(charts["country"].unique())

['ar',
 'at',
 'au',
 'be',
 'br',
 'ca',
 'ch',
 'cl',
 'co',
 'cz',
 'de',
 'dk',
 'do',
 'ec',
 'es',
 'fi',
 'fr',
 'gb',
 'global',
 'gt',
 'hk',
 'hu',
 'id',
 'ie',
 'in',
 'it',
 'jp',
 'kz',
 'mx',
 'my',
 'ng',
 'nl',
 'no',
 'nz',
 'pa',
 'pe',
 'ph',
 'pk',
 'pl',
 'ro',
 'se',
 'sg',
 'sk',
 'th',
 'tr',
 'tw',
 'ua',
 'us',
 've',
 'vn',
 'za']

In [6]:
charts["artist_names"].nunique()

12249

In [7]:
charts["album_name"].nunique()

25274

In [8]:
charts["entry_status"].value_counts()

entry_status
MOVED_DOWN    1533796
MOVED_UP      1061821
NO_CHANGE      212005
RE_ENTRY       107353
NEW_ENTRY       74200
Name: count, dtype: int64

In [9]:
charts.groupby(
    ["album_name", "artist_names"]
)["weeks_on_chart"].max()\
.sort_values(ascending=False)\
.head(20)

album_name                                             artist_names
Hamilton (Original Broadway Cast Recording)            Lin-Manuel Miranda    313
Take Care (Deluxe)                                     Drake                 313
2014 Forest Hills Drive (10 Year Anniversary Edition)  J. Cole               313
Rumours (Super Deluxe)                                 Fleetwood Mac         313
Graduation (Deluxe Edition - Explicit)                 Kanye West            313
21                                                     Adele                 313
DAMN.                                                  Kendrick Lamar        313
Goodbye & Good Riddance (5 Year Anniversary Edition)   Juice WRLD            313
Ctrl (Deluxe)                                          SZA                   313
÷ (Deluxe)                                             Ed Sheeran            313
Hozier (Special Edition)                               Hozier                313
Hybrid Theory (20th Anniversary Edition)               Linkin Park           313
Hollywood's Bleeding                                   Post Malone           313
Teenage Dream: The Complete Confection                 Katy Perry            313
My Beautiful Dark Twisted Fantasy (Edited Version)     Kanye West            313
Blonde                                                 Frank Ocean           313
Legends Never Die (5 Year Anniversary Edition)         Juice WRLD            313
Future Nostalgia (The Moonlight Edition)               Dua Lipa              313
good kid, m.A.A.d city (Deluxe)                        Kendrick Lamar        313
Purpose (Deluxe)                                       Justin Bieber         313
Name: weeks_on_chart, dtype: int64

In [10]:
charts["movement"] = (
    charts["previous_rank"] -
    charts["rank"]
)

charts.sort_values(
    "movement",
    ascending=False
)[
    [
        "date",
        "album_name",
        "artist_names",
        "previous_rank",
        "rank",
        "movement"
    ]
].head(20)

,date,album_name,artist_names,previous_rank,rank,movement
2661187,2021-05-06,FREERIO,OG Buda,199,1,198
1516187,2026-04-16,Vangelo,Shiva,199,1,198
216600,2024-12-12,JVLIVS III : Ad Finem,SCH,199,1,198
2935779,2026-06-18,you seem pretty sad for a girl so in love,Olivia Rodrigo,200,5,195
2566191,2023-05-25,Dünya,Yıldız Usmonova,199,5,194
976400,2025-06-05,BĒYĀH,Damso,195,1,194
2294988,2025-09-04,Man’s Best Friend,Sabrina Carpenter,195,2,193
107001,2025-09-04,Man’s Best Friend,Sabrina Carpenter,195,2,193
2652792,2026-04-16,My World 2.0,Justin Bieber,198,6,192
2279589,2024-03-14,Vise Lucide,Bvcovia,195,3,192
1748389,2022-08-25,The Guy,M.I. Abaga,195,3,192
2191190,2021-05-13,Diamentowy Las,Białas|White 2115,194,4,190
2832376,2022-02-10,Hope World,j-hope,192,2,190
1516390,2026-05-07,Nerissima,Nerissima Serpe,194,4,190
480805,2021-12-09,Sauce Boyz 2,Eladio Carrion,196,6,190
463007,2025-12-25,Navidades Luis Miguel,Luis Miguel,197,8,189
1055795,2021-07-22,All Over The Place (Platinum VIP Edition),KSI,198,9,189
1476788,2022-06-09,Hustle Mixtape,Capo Plaza,191,2,189
1774992,2025-04-03,Deep Thoughts,Lil Durk,194,6,188
2469987,2025-06-12,brat,Pil C|Luca Brassi10x,189,1,188

In [11]:
charts["country"].nunique()

51

In [12]:
charts["date"].agg(["min", "max"])

min   2020-10-22
max   2026-10-08
Name: date, dtype: datetime64[ns]

In [13]:
charts.isnull().sum().sort_values(ascending=False)

release_date         83901
album_name            1599
label                 1559
artist_names          1542
country                  0
date                     0
rank                     0
peak_rank                0
previous_rank            0
uri                      0
weeks_on_chart           0
consecutive_weeks        0
peak_date                0
entry_status             0
entry_rank               0
entry_date               0
artist_uris              0
movement                 0
dtype: int64

In [14]:
charts["entry_status"].value_counts()

entry_status
MOVED_DOWN    1533796
MOVED_UP      1061821
NO_CHANGE      212005
RE_ENTRY       107353
NEW_ENTRY       74200
Name: count, dtype: int64

In [15]:
charts["country"].value_counts().head(20)

country
cz        60800
cl        60600
id        60600
sk        60600
us        60588
global    60587
co        60400
ro        60400
ph        60400
pl        60400
es        60200
gt        60200
jp        60200
fi        60200
pa        60200
mx        60200
za        60200
gb        60000
ar        60000
my        60000
Name: count, dtype: int64

In [16]:
(
    charts.groupby(
        ["album_name", "artist_names"]
    )["weeks_on_chart"]
    .max()
    .sort_values(ascending=False)
    .head(20)
)

album_name                                             artist_names
Hamilton (Original Broadway Cast Recording)            Lin-Manuel Miranda    313
Take Care (Deluxe)                                     Drake                 313
2014 Forest Hills Drive (10 Year Anniversary Edition)  J. Cole               313
Rumours (Super Deluxe)                                 Fleetwood Mac         313
Graduation (Deluxe Edition - Explicit)                 Kanye West            313
21                                                     Adele                 313
DAMN.                                                  Kendrick Lamar        313
Goodbye & Good Riddance (5 Year Anniversary Edition)   Juice WRLD            313
Ctrl (Deluxe)                                          SZA                   313
÷ (Deluxe)                                             Ed Sheeran            313
Hozier (Special Edition)                               Hozier                313
Hybrid Theory (20th Anniversary Edition)               Linkin Park           313
Hollywood's Bleeding                                   Post Malone           313
Teenage Dream: The Complete Confection                 Katy Perry            313
My Beautiful Dark Twisted Fantasy (Edited Version)     Kanye West            313
Blonde                                                 Frank Ocean           313
Legends Never Die (5 Year Anniversary Edition)         Juice WRLD            313
Future Nostalgia (The Moonlight Edition)               Dua Lipa              313
good kid, m.A.A.d city (Deluxe)                        Kendrick Lamar        313
Purpose (Deluxe)                                       Justin Bieber         313
Name: weeks_on_chart, dtype: int64

In [17]:
charts["movement"] = (
    charts["previous_rank"] -
    charts["rank"]
)

charts.sort_values(
    "movement",
    ascending=False
)[
    [
        "date",
        "album_name",
        "artist_names",
        "country",
        "previous_rank",
        "rank",
        "movement"
    ]
].head(20)

,date,album_name,artist_names,country,previous_rank,rank,movement
2661187,2021-05-06,FREERIO,OG Buda,ua,199,1,198
1516187,2026-04-16,Vangelo,Shiva,it,199,1,198
216600,2024-12-12,JVLIVS III : Ad Finem,SCH,be,199,1,198
2935779,2026-06-18,you seem pretty sad for a girl so in love,Olivia Rodrigo,za,200,5,195
2566191,2023-05-25,Dünya,Yıldız Usmonova,tr,199,5,194
976400,2025-06-05,BĒYĀH,Damso,fr,195,1,194
2294988,2025-09-04,Man’s Best Friend,Sabrina Carpenter,ro,195,2,193
107001,2025-09-04,Man’s Best Friend,Sabrina Carpenter,at,195,2,193
2652792,2026-04-16,My World 2.0,Justin Bieber,tw,198,6,192
2279589,2024-03-14,Vise Lucide,Bvcovia,ro,195,3,192
1748389,2022-08-25,The Guy,M.I. Abaga,ng,195,3,192
2191190,2021-05-13,Diamentowy Las,Białas|White 2115,pl,194,4,190
2832376,2022-02-10,Hope World,j-hope,vn,192,2,190
1516390,2026-05-07,Nerissima,Nerissima Serpe,it,194,4,190
480805,2021-12-09,Sauce Boyz 2,Eladio Carrion,co,196,6,190
463007,2025-12-25,Navidades Luis Miguel,Luis Miguel,cl,197,8,189
1055795,2021-07-22,All Over The Place (Platinum VIP Edition),KSI,global,198,9,189
1476788,2022-06-09,Hustle Mixtape,Capo Plaza,it,191,2,189
1774992,2025-04-03,Deep Thoughts,Lil Durk,ng,194,6,188
2469987,2025-06-12,brat,Pil C|Luca Brassi10x,sk,189,1,188

In [18]:
df = charts[
    [
        "date",
        "country",
        "rank",
        "album_name",
        "artist_names",
        "peak_rank",
        "previous_rank",
        "weeks_on_chart",
        "consecutive_weeks",
        "entry_status"
    ]
].copy()

In [19]:
df["date"] = pd.to_datetime(df["date"])

In [22]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2989175 entries, 0 to 2989174
Data columns (total 10 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[ns]
 1   country            object
 2   rank               int64
 3   album_name         object
 4   artist_names       object
 5   peak_rank          int64
 6   previous_rank      int64
 7   weeks_on_chart     int64
 8   consecutive_weeks  int64
 9   entry_status       object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 816.5 MB

In [23]:
print(
    round(
        df.memory_usage(deep=True).sum() / 1024**2,
        2
    ),
    "MB"
)

816.49 MB

In [24]:
keep_cols = [
    "date",
    "country",
    "rank",
    "album_name",
    "artist_names",
    "peak_rank",
    "previous_rank",
    "weeks_on_chart",
    "consecutive_weeks",
    "entry_status",
]

In [25]:
chartpulse = df[keep_cols].copy()

In [30]:
import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(
    page_title="ChartPulse",
    page_icon="🎵",
    layout="wide"
)

st.title("🎵 ChartPulse")
st.subheader("Spotify Album Trends Explorer")

@st.cache_data
def load_data():
    return pd.read_csv(
        "charts_albums_weekly.csv",
        low_memory=False
    )

df = load_data()

# Sidebar
countries = sorted(df["country"].unique())

selected_country = st.sidebar.selectbox(
    "Country",
    countries
)

filtered_df = df[
    df["country"] == selected_country
].copy()

# KPI Cards
col1, col2, col3 = st.columns(3)

col1.metric(
    "Albums",
    filtered_df["album_name"].nunique()
)

col2.metric(
    "Artists",
    filtered_df["artist_names"].nunique()
)

col3.metric(
    "Rows",
    f"{len(filtered_df):,}"
)

st.divider()

# Longest Charting Albums
st.header("🏆 Longest Charting Albums")

longevity = (
    filtered_df.groupby(
        ["album_name", "artist_names"]
    )["weeks_on_chart"]
    .max()
    .reset_index()
    .sort_values(
        "weeks_on_chart",
        ascending=False
    )
    .head(20)
)

fig = px.bar(
    longevity,
    x="weeks_on_chart",
    y="album_name",
    color="weeks_on_chart",
    orientation="h",
    hover_data=["artist_names"],
    title="Top 20 Albums by Weeks on Chart"
)

fig.update_layout(
    yaxis={
        "categoryorder": "total ascending"
    }
)

st.plotly_chart(
    fig,
    use_container_width=True
)

ModuleNotFoundError: No module named 'streamlit'